### ISSUE TITLE
大佬，这个是没有适配jdk17吗

### ISSUE THREAD

**Issue by lianlonggang** [noear/luffy#1]
```java
Solon start failed: Cannot invoke "javax.script.ScriptEngine.getBindings(int)" because "this._eng" is null
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.getBindings(int)" because "this._eng" is null
	at org.noear.luffy.executor.s.javascript.JavascriptJtExecutor.<init>(JavascriptJtExecutor.java:53)
	at org.noear.luffy.executor.s.javascript.JavascriptJtExecutor.singleton(JavascriptJtExecutor.java:31)
	at org.noear.luffy.executor.s.javascript.XPluginImp.start(XPluginImp.java:11)
	at org.noear.solon.core.PluginEntity.start(PluginEntity.java:108)
	at org.noear.solon.SolonApp.run(SolonApp.java:202)
	at org.noear.solon.SolonApp.start(SolonApp.java:114)
	at org.noear.solon.Solon.start(Solon.java:158)
	at watersev.WatersevApp.main(WatersevApp.java:67)
```

**Comment by noear** [comment]
executor.s.javascript，只支持 java9 到 java14；；；超过 14 的，估计要换成： luffy.executor.s.nashorn 执行器

**Comment by noear** [comment]
这不是推广项目，没什么资料。。。不建议使用
